name: Deploy to Salesforce

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
          fetch-depth: 1

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: CLI Version
        run: sf --version

      - name: Authenticate DevOrgB
        run: |
          printf "%s" "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias DevOrgB
          sf org display --target-org DevOrgB

      - name: Deploy Metadata
        run: |
          sf project deploy start --target-org DevOrgB --wait 30 --verbose